dist: bionic
language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: i14bngeQTFZS24xHauwDOD4fzEqOezbiGLLuz2hTcQy7hCwfP1Tq/4onvt/iArcbOFTzJ1zGR4MrdPb9z8r6N52vlTvhRqgXzjsRBCFPqweFricGup+EPOwV1ptW6Ws/YLuZzl59nvw1kPJollvFVpfdeqnBmPb32BvJxfENWDryJZFT9HaTD/vjqOXvsFGWjVKWwHkVI+4d0zgM0Za5SSdWw6mC2x2m6SSZpFbD2SdxF1pGuUbt38k9q3GixlEfptw8ov3jxCj4nc2zRIi4GJDBWYlj66ODa+yJUEJ1Dt8Q0XMwDxpTCDK5Y5UJdn3ARxlNSYe0dWcBUjoqof0p0ZLcmoit23Cw8qd1Xzu/iOLsaE6SbWxYhcL5QXXHQiG0yEbf3067fFuRSOmlQLyWsGCL8Svxh7uPis+5SUhsYJwODqcR2yBjkL3XfOofcvi4pc/oKUWXe9GKm4DQCR9B/MGTNvDSvantQWpym5gPuIUndtwEV3w3o73E/YVTSt0Sna4IcH5xMnklX9c5o+2ryz8TgtQg/998mbvMiSEShpyaNYoEBFkXrEepi12bbgwg8uVCs4z980o2pgWuDuLPCr+2kncud9kY9aZzjUT5pK8WNYr+zbTQ9tzlx/m9FcYlL55Ep+M1vQ3I07RjoY4bCYD5HxLKbqa/wq2hfz9o7Ho=
  on:
    all_branches: true
    branch: master
    tags: true
    repo: PhosphorylatedRabbits/pimkl
    python: 3.7
